spring:
  application:
    name: ExchangeXP

  data:
    mongodb:
      uri: ${MONGO_URI}
#      host: localhost
#      port: 27017
      database: ExchangeXP
      auto-index-creation: true

logging:
  level:
    com:
      Shinigami_Coderz:
        ExchangeXP:
          com.Shinigami_Coderz.ExchangeXP.ExchangeXPt: trace

# Firebase service account file (local dev). Leave empty to use GOOGLE_APPLICATION_CREDENTIALS env var
firebase:
  service-account-file: ${FIREBASE_JSON}