spring:
  application:
    name: ExchangeXP

server:
  port: ${PORT}

  data:
    mongodb:
      uri: ${MONGO_URI}
#      host: localhost
#      port: 27017
      database: ExchangeXP
      auto-index-creation: true

logging:
  level:
    com:
      Shinigami_Coderz:
        ExchangeXP:
          com.Shinigami_Coderz.ExchangeXP.ExchangeXPt: trace

firebase:
  service-account-file: ${FIREBASE_JSON}
